Grupp4/Game21V2/Models/GameOf21.cs
using System;

namespace Game21V2.Models
{
    public class GameOf21
    {
        public int Total { get; set; } = 0;
        public string Announcement { get; set; }

        public void AddNr(int tal)
        {
            if (Total <= 21)
            {
                Total += tal;
                if (Total == 21)
                {
                    Announcement = "You Win!!";
                }
            }

            Computer();
        }

        private void Computer()
        {
            if (Total >= 12)
            {
                Total += (Total + 1)%3 == 0 ? 1 : 2;
                if (Total == 21)
                {
                    Announcement = "Computer Won!!";
                }
            }

            if (Total < 12)
            {
                var random = new Random();
                Total += random.Next(1, 3);
            }
        }
    }
}

Grupp4/Game21V2/Controllers/Game21Controller.cs
using System.Web.Mvc;
using Game21V2.Models;

namespace Game21V2.Controllers
{
    public class Game21Controller : Controller
    {
        // GET: Game21
        public ActionResult Index()
        {
            var game21 = new GameOf21();
            this.Session["game21"] = game21;

            return View(game21);
        }

        [HttpPost]
        public ActionResult Index(int? add)
        {
            var game21 = (GameOf21)this.Session["game21"];
            game21.AddNr(add.Value);
            return View(game21);
        }

    }
}

Grupp4/Game21V2/Views/Game21/Index.cshtml
@model Game21V2.Models.GameOf21

@{
    ViewBag.Title = "Index";
}

<h2>Game Of 21</h2>
<h3>@Model.Announcement</h3>

@using (Html.BeginForm("Index", "Game21"))
{
    <h1>@Model.Total</h1><br />

    <button type="submit" value="1" name="Add" class="btn btn-secondary">1</button>
    <button type="submit" value="2" name="Add" class="btn btn-secondary">2</button><br />
}