Grupp4/Grupp4/Controllers/Game1Controller.cs
using Grupp4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Grupp4.Controllers
{
    public class Game1Controller : Controller
    {
        // GET: Game1
        public ActionResult Index()

        {
            var model = new Game1Model();
            model.Start();

            return View(model);
        }
        [HttpPost]

        public ActionResult Index(Game1Model model)

        {
            model.PlayerAddCurrentValue();
            if (model.PlayerIsWinner())

            {

                ViewBag.Result = "You win.";
            }
            model.ComputerAddCurrentValue();
            if (model.ComputerIsWinner())

            {
                ViewBag.Result = "Computer wins.";
                model.CurrentValue = 0;
            }
            ModelState.Remove("CurrentValue");

            return View(model);
        }

       

    }

}

Grupp4/Grupp4/Views/Game1/Index.cshtml
@model Grupp4.Models.Game1Model
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Game 21</h2>

@if (ViewBag.Result != null)

{

    <p>@ViewBag.Result</p>

}

@using (Html.BeginForm("Index", "Game1"))

{

    @Html.HiddenFor(x => x.CurrentValue);
    <p>Computer added with: @Html.DisplayTextFor(c => c.Computer)</p>
    <p>Player added with: @Html.DisplayTextFor(p => p.ChoosenNumber)</p>

    @Html.DisplayTextFor(x => x.CurrentValue);



    <br />

    <label for="nummer1">1</label>

    @Html.RadioButtonFor(x => x.ChoosenNumber, "1", new { id = "nummer1" })

    <label for="number2">Eller 2</label>

    @Html.RadioButtonFor(x => x.ChoosenNumber, "2", new { id = "nummer2" })

    <br />

    <input type="submit" value="Lägg till en siffra" />

}